context:
  version: 21.0.0

package:
  name: tapjs
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/tap/-/tap-${{ version }}.tgz
  sha256: ab35dabbcba62b7140484b747bab83e7aa420ff61fbd1e22856d53aba25af2e3

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - tap --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Test Anything Protocol tools for node
  homepage: https://github.com/tapjs/tapjs
  repository: https://github.com/tapjs/tapjs

extra:
  recipe-maintainers:
    - danielnachun
