context:
  version: "21.1.3"

package:
  name: tapjs
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/tap/-/tap-${{ version }}.tgz
  sha256: 84454359cbbd69061fd6c833d61ea27090856c6a04337d8d40d6b2002ec0ccad

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - tap --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Test Anything Protocol tools for node
  homepage: https://github.com/tapjs/tapjs
  repository: https://github.com/tapjs/tapjs

extra:
  recipe-maintainers:
    - danielnachun
