context:
  version: "21.1.1"

package:
  name: tapjs
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/tap/-/tap-${{ version }}.tgz
  sha256: c2f525aa41acba06d9e735b81f180d8e59840495f78e21bb151bc83968b465f3

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - tap --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Test Anything Protocol tools for node
  homepage: https://github.com/tapjs/tapjs
  repository: https://github.com/tapjs/tapjs

extra:
  recipe-maintainers:
    - danielnachun
