context:
  version: "21.0.2"

package:
  name: tapjs
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/tap/-/tap-${{ version }}.tgz
  sha256: 3b54c2fbdd6e7919943222b1c7341ed841467b8ebf632fc66a875793914ac89e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - tap --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Test Anything Protocol tools for node
  homepage: https://github.com/tapjs/tapjs
  repository: https://github.com/tapjs/tapjs

extra:
  recipe-maintainers:
    - danielnachun
